mitchell-merry/emu-viewer

src/main.py
Allow the ability to open multiple images in 2 column table
=> Some more ui tests

README.md
This PR clarifies the readme with more steps for installing make
=> Add more steps in readme

requirements.txt, src/main.py, src/widgets/image_controller.py
=> Tkkbootstrap test

src/main.py
handles the error when cancel is selected
=> Handle cancel on file open dialogue

data/sample/.gitignore, src/lib/event_handler.py, src/main.py, src/widgets/image_controller.py, tests/test_event_handler.py
This is a bit terser syntax for event handling which we might use throughout the project.
To setup an EventHandler, just construct it like
```py
open_file = EventHandler()
```
Then, consumers which want to hook into this event can listen like so
```py
open_file.add(my_func)
```
Then we can invoke the event by calling:
```py
open_file.invoke(...args...)
```
In this example, open_file is setup inside MenuBar, ImageController adds itself to this event in __init__, and MenuBar invokes the listeners inside it's open file method.
=> Refactor how events work with custom EventHandler class

src/main.py
added if statement to catch error for empty filename
=> Added early return for empty filename

.gitignore, src/controllers/image_controller.py, src/widgets/image_widget.py
Not super smooth, but we'll take it
=> Implement panning and zooming

src/controllers/data_controller.py, src/controllers/image_controller.py, src/controllers/widget_controller.py, src/lib/event_handler.py, src/main.py, src/widgets/histogram_widget.py, src/widgets/image_table_widget.py, src/widgets/menu_bar.py, src/widgets/tool_bar.py
-Removed panned windows
-Added support for external toplevel widgets/seperate windows(Added histogram and image table as examples can be edited as needed)
=> PX12-87 # Finished basic UI

.gitignore, Makefile, README.md, requirements.txt, src/controllers/image_controller.py, src/lib/render.py, src/lib/util.py, src/widgets/image_widget.py
now instead of using a mpl figure we render out to a .png and create it on a tkinter canvas
panning is much faster but zooming is slower
extracts out rendering to a separate script, we should be able to pass config to that func
uses a new library pyvips that will need to be manually installed
=> PX12-85 PX12-88 PX12-90 Render images as .pngs and pan that instead

src/controllers/image_controller.py, src/lib/render.py, src/main.py, src/widgets/image_widget.py, src/widgets/menu_bar.py
small update in image controller, 2nd option to open an image but it appears in a new window. Replaces tabbed images and append function within carter
=> windows update

.gitignore, src/controllers/image_controller.py, src/lib/render.py, src/main.py, src/widgets/image_standalone_toplevel.py, src/widgets/image_widget.py
You can now get the currently selected image through `ImageController#get_selected_image`. You can also now get the fits file of that image through `ImageFrame#fits_file`.
=> NONE Expose selected image from image controller

src/widgets/renderer_widget.py
- Completed the basic UI of the render configuration UI
=> PX12-110 # Render Configuration UI

src/controllers/image_controller.py, src/controllers/widget_controller.py, src/lib/render.py, src/widgets/image_standalone_toplevel.py, src/widgets/image_widget.py, src/widgets/menu_bar.py, src/widgets/renderer_widget.py
- The ability to change the colour map, the histogram scaling and the scaling of a selected image has been added to the render widget
=> PX12-97 # Allow changing of render configuration

src/widgets/image_widget.py
=> Add WCS coords to debug tooltip

requirements.txt, src/controllers/image_controller.py, src/controllers/widget_controller.py, src/lib/fits_handler.py, src/lib/hips_handler.py, src/lib/render.py, src/widgets/hips_selector_widget.py, src/widgets/image_standalone_toplevel.py, src/widgets/image_widget.py, src/widgets/menu_bar.py, src/widgets/renderer_widget.py
Support for Hips files added
- The ability to select from a multitude of hips surveys
- The ability to choose all options required generate a hips survey
=> PX12-97 # Handling of Hips survey

pyproject.toml, resources/data/.gitignore, src/controllers/image_controller.py, src/controllers/widget_controller.py, src/widgets/base_widget.py, src/widgets/contour_widget.py, src/widgets/hips_selector_widget.py, src/widgets/image_standalone_toplevel.py, src/widgets/image_table_widget.py, src/widgets/menu_bar.py, src/widgets/renderer_widget.py
=> Widget controller

src/controllers/widget_controller.py, src/widgets/menu_bar.py
This fixes an issue with the widget controller where we are inconsistently using keys for open_windows.
=> Fixes Widget Controller

src/controllers/image_controller.py, src/controllers/widget_controller.py, src/widgets/image_table_widget.py
Widget controller actually lets you re-open windows now
Image table handles no images
Also fixes image number on table
=> Three minor issues

src/controllers/widget_controller.py, src/main.py
As title says. This was fairly easy to implement
=> PX12-113 PX12-114 Focus widget on open & open render configuration on app startup

src/controllers/image_controller.py, src/lib/render.py, src/widgets/image_widget.py, src/widgets/renderer_widget.py
- change min/max to be raw values and not percentile
- update those values when a percentile is selected
- fix some rando bugs
=> PX12-122 Fix min/max fields on renderer config

src/controllers/image_controller.py, src/main.py, src/widgets/base_widget.py, src/widgets/image_standalone_toplevel.py, src/widgets/image_widget.py, src/widgets/menu_bar.py, src/widgets/renderer_widget.py, src/widgets/tool_bar.py
=> PX12-127 Change from open / append to open / close

resources/data/.gitignore, src/widgets/contour_widget.py, src/widgets/renderer_widget.py
PR for another PR https://github.com/mitchell-merry/emu-viewer/pull/49. Contains fixes for issues raised in that PR
=> Make UI more resilient to png files

src/lib/tool.py
Decided to be brave today and open this PR the day before our meeting :P
This PR overrides the tool bar's save_figure method so that it saves only the actual image, not the stuff around it (ticks, co-ords, labels, etc).
=> PX12-100 Export only the actual image

docs/bugs.txt, docs/outstanding_features.txt, resources/data/.gitignore, src/controllers/image_controller.py, src/lib/hips_handler.py, src/lib/png_handler.py, src/lib/render.py, src/widgets/catalogue_widget.py, src/widgets/contour_widget.py, src/widgets/hips_selector_widget.py, src/widgets/image_standalone_toplevel.py, src/widgets/image_widget.py, src/widgets/menu_bar.py, src/widgets/renderer_widget.py, src/widgets/statistics_widget.py
=> PX12-95 Open png files

src/lib/render.py, src/lib/tool.py
Implements the below
https://github.com/mitchell-merry/emu-viewer/assets/8567231/21dbe8a1-b055-4a47-af7a-76513cdb1fd3
=> PX12-125 Add all co-ordinate formats to tooltip

src/lib/contour_handler.py, src/widgets/contour_widget.py
Title!
Slowly working on documenting methods.
=> PX12-133 Change the default sigma value to be clipped at 2.5x standard deviation

src/lib/match_type.py, src/widgets/base_widget.py, src/widgets/components/table_widget.py, src/widgets/image_table_widget.py, src/widgets/image_widget.py
- show buttons for matching in the table
- highlight currently selected image (bolded)
- click a row to select an image
=> PX-144 PX-119 Add buttons in the image table for render matching

src/lib/render.py, src/lib/tool.py
=> PX12-130 PX12-131 Revert save override, re-add value

src/lib/render.py, src/widgets/image_widget.py, src/widgets/renderer_widget.py
This PR adds the histogram to the render widget
Still to add is the option to change the vmin and vmax values
=> PX12-99 PX12-142 - Histogram added to render widget

src/widgets/renderer_widget.py
=> PX12-145 Fix gridlines (proper disabling)

src/lib/render.py, src/widgets/image_widget.py
RENDER CONFIG
SLOW RIGHT NOW
WILL MAKE FASTER
=> Vispy render config

.github/workflows/release.yml, src/constants.py, src/lib/tool.py
Forgot to remove ASSETS_FOLDER in the annotations PR, this should now be using our nice system for getting the path.
=> PX12-150 Fix mac builds

.github/workflows/release.yml, README.md, requirements-dev.txt, requirements.txt
tries a few things to see if it improves our release
=> PX12-151 PX12-153 Try a couple things to see if it improves the output

src/lib/render.py, src/lib/tool.py, src/widgets/image_widget.py, src/widgets/renderer_widget.py
Fixed a few small issues with the histogram
=> Histogram Fixes

src/lib/render.py, src/widgets/image_widget.py
Image coordinates copies correctly and works. WCS needs a little debugging. There are no errors with code.
=> Context Menu - Mostly Done

src/constants.py, src/controllers/widget_controller.py, src/main.py, src/widgets/base_widget.py, src/widgets/image_standalone_toplevel.py
No ticket for this but a couple small changes
=> Polishing the favicon and the focusing

src/widgets/components/table_widget.py, src/widgets/image_widget.py
=> Context menu improvements

src/lib/tool.py
Changed toolbar buttons on image and histo from tk buttons tkkbootstrap buttons
=> [Draft] Fixed toolbar buttons

src/lib/hips_handler.py, src/widgets/hips_selector_widget.py
Added more validation to the hips selector and some comments to the hips selector and hips handler
=> PX12-154 Hips selector updates

src/controllers/image_controller.py, src/controllers/widget_controller.py, src/enums.py, src/lib/fits_handler.py, src/lib/hips_handler.py, src/lib/match_type.py, src/lib/render.py, src/main.py, src/widgets/catalogue_widget.py, src/widgets/contour_widget.py, src/widgets/hips_selector_widget.py, src/widgets/image_standalone_toplevel.py, src/widgets/image_table_widget.py, src/widgets/image_widget.py, src/widgets/menu_bar.py, src/widgets/renderer_widget.py, src/widgets/statistics_widget.py, tests/test_contour_widget.py
And make the hips survey message box non-blocking
=> PX12-117 Refactor image controller to not be a class

src/lib/tool.py
Fix image flickering by not resetting theme for every toolbar button, whoops my bad
=> Fix image flickering

src/controllers/widget_controller.py, src/main.py, src/widgets/image_table_widget.py, src/widgets/image_widget.py, src/widgets/menu_bar.py
also fixes a bug with the hips survey selector from the last PR
=> PX12-117 Refactor widget controller to be not a class

src/components/image_frame.py, src/lib/render.py, src/lib/tool.py, src/widgets/image_widget.py
Fixed the render buttons to no longer reset vmin and vmax when going home or backwards
=> PX12-163 Fixed render buttons

src/_overrides/ttkbootstrap/CatalogueTableView.py, src/widgets/catalogue/catalogue.py, src/widgets/catalogue/catalogue_widget.py
Updated catalogue buttons and removed unneeded reset options in data table
Comment catalogue widget and catalogue
=> Updated catalogue

src/widgets/image/fits_handler.py, src/widgets/image/image_frame.py, src/widgets/renderer/renderer_widget.py
Grid lines now match when render matching is set
Fixed out of bounds issue when rounding x and y value for displayed value
=> PX12-162 Grid lines update

src/_overrides/matplotlib/ImageToolbar.py, src/menu_bar.py, src/widgets/catalogue/catalogue_widget.py, src/widgets/contour/contour_widget.py, src/widgets/hips_survey_selector/hips_handler.py, src/widgets/hips_survey_selector/hips_selector_widget.py, src/widgets/image/image_controller.py, src/widgets/image/image_standalone_menubar.py, src/widgets/renderer/renderer_widget.py, src/widgets/widget_controller.py
- Actually disable the menu bars on mac since it looks fine / worksbetter
- Add defaults to the colour button string vars in catalogue / annotations
- Hips to HiPs
- widen catalogue widget & make the buttons the same as on contours
- contour widget and such no longer get scientific notation put in
-
=> PX12-66 FIX SOME ISSUES!!!

src/_overrides/matplotlib/ImageToolbar.py, src/widgets/image/image_controller.py, src/widgets/image/image_frame.py
Fixed not catching incorrect data type for hips survey
Changed text annotation pop up from tkinter to ttkbootstrap to make it look nicer on macOS
=> Some more fixes for various things

src/enums.py, src/widgets/contour/contour.py, src/widgets/image/fits_handler.py
Reverted the change that fixed the render config changing when interacting with the history buttons
Fixed contour lines not sorting correctly
=> Minor fixes that were uncovered during demo practice
